# Generated by Django 2.2 on 2019-11-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0011_auto_20191121_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='titulo',
            field=models.CharField(default='comentario', max_length=30, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(max_length=255, verbose_name='comentario'),
        ),
    ]
