# Generated by Django 2.2 on 2019-11-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0014_auto_20191122_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de compra'),
        ),
    ]
