# Generated by Django 2.2.7 on 2019-11-18 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUser', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('ciudad', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='id_product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nombre',
            new_name='nombreP',
        ),
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(max_length=150)),
                ('pub_date', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.Usuario')),
            ],
        ),
    ]
